// Copyright (c) 2004-present Facebook All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/facebookincubator/symphony/pkg/ent/filecategorytype"
	"github.com/facebookincubator/symphony/pkg/ent/locationtype"
	"github.com/facebookincubator/symphony/pkg/ent/predicate"
)

// FileCategoryTypeQuery is the builder for querying FileCategoryType entities.
type FileCategoryTypeQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.FileCategoryType
	// eager-loading edges.
	withLocationType *LocationTypeQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (fctq *FileCategoryTypeQuery) Where(ps ...predicate.FileCategoryType) *FileCategoryTypeQuery {
	fctq.predicates = append(fctq.predicates, ps...)
	return fctq
}

// Limit adds a limit step to the query.
func (fctq *FileCategoryTypeQuery) Limit(limit int) *FileCategoryTypeQuery {
	fctq.limit = &limit
	return fctq
}

// Offset adds an offset step to the query.
func (fctq *FileCategoryTypeQuery) Offset(offset int) *FileCategoryTypeQuery {
	fctq.offset = &offset
	return fctq
}

// Order adds an order step to the query.
func (fctq *FileCategoryTypeQuery) Order(o ...OrderFunc) *FileCategoryTypeQuery {
	fctq.order = append(fctq.order, o...)
	return fctq
}

// QueryLocationType chains the current query on the location_type edge.
func (fctq *FileCategoryTypeQuery) QueryLocationType() *LocationTypeQuery {
	query := &LocationTypeQuery{config: fctq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fctq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fctq.sqlQuery()
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(filecategorytype.Table, filecategorytype.FieldID, selector),
			sqlgraph.To(locationtype.Table, locationtype.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, filecategorytype.LocationTypeTable, filecategorytype.LocationTypeColumn),
		)
		fromU = sqlgraph.SetNeighbors(fctq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FileCategoryType entity in the query. Returns *NotFoundError when no filecategorytype was found.
func (fctq *FileCategoryTypeQuery) First(ctx context.Context) (*FileCategoryType, error) {
	nodes, err := fctq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{filecategorytype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fctq *FileCategoryTypeQuery) FirstX(ctx context.Context) *FileCategoryType {
	node, err := fctq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FileCategoryType id in the query. Returns *NotFoundError when no id was found.
func (fctq *FileCategoryTypeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fctq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{filecategorytype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fctq *FileCategoryTypeQuery) FirstIDX(ctx context.Context) int {
	id, err := fctq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only FileCategoryType entity in the query, returns an error if not exactly one entity was returned.
func (fctq *FileCategoryTypeQuery) Only(ctx context.Context) (*FileCategoryType, error) {
	nodes, err := fctq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{filecategorytype.Label}
	default:
		return nil, &NotSingularError{filecategorytype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fctq *FileCategoryTypeQuery) OnlyX(ctx context.Context) *FileCategoryType {
	node, err := fctq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID returns the only FileCategoryType id in the query, returns an error if not exactly one id was returned.
func (fctq *FileCategoryTypeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fctq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{filecategorytype.Label}
	default:
		err = &NotSingularError{filecategorytype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fctq *FileCategoryTypeQuery) OnlyIDX(ctx context.Context) int {
	id, err := fctq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FileCategoryTypes.
func (fctq *FileCategoryTypeQuery) All(ctx context.Context) ([]*FileCategoryType, error) {
	if err := fctq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return fctq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (fctq *FileCategoryTypeQuery) AllX(ctx context.Context) []*FileCategoryType {
	nodes, err := fctq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FileCategoryType ids.
func (fctq *FileCategoryTypeQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := fctq.Select(filecategorytype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fctq *FileCategoryTypeQuery) IDsX(ctx context.Context) []int {
	ids, err := fctq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fctq *FileCategoryTypeQuery) Count(ctx context.Context) (int, error) {
	if err := fctq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return fctq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (fctq *FileCategoryTypeQuery) CountX(ctx context.Context) int {
	count, err := fctq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fctq *FileCategoryTypeQuery) Exist(ctx context.Context) (bool, error) {
	if err := fctq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return fctq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (fctq *FileCategoryTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := fctq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fctq *FileCategoryTypeQuery) Clone() *FileCategoryTypeQuery {
	if fctq == nil {
		return nil
	}
	return &FileCategoryTypeQuery{
		config:           fctq.config,
		limit:            fctq.limit,
		offset:           fctq.offset,
		order:            append([]OrderFunc{}, fctq.order...),
		unique:           append([]string{}, fctq.unique...),
		predicates:       append([]predicate.FileCategoryType{}, fctq.predicates...),
		withLocationType: fctq.withLocationType.Clone(),
		// clone intermediate query.
		sql:  fctq.sql.Clone(),
		path: fctq.path,
	}
}

//  WithLocationType tells the query-builder to eager-loads the nodes that are connected to
// the "location_type" edge. The optional arguments used to configure the query builder of the edge.
func (fctq *FileCategoryTypeQuery) WithLocationType(opts ...func(*LocationTypeQuery)) *FileCategoryTypeQuery {
	query := &LocationTypeQuery{config: fctq.config}
	for _, opt := range opts {
		opt(query)
	}
	fctq.withLocationType = query
	return fctq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FileCategoryType.Query().
//		GroupBy(filecategorytype.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (fctq *FileCategoryTypeQuery) GroupBy(field string, fields ...string) *FileCategoryTypeGroupBy {
	group := &FileCategoryTypeGroupBy{config: fctq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := fctq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return fctq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.FileCategoryType.Query().
//		Select(filecategorytype.FieldCreateTime).
//		Scan(ctx, &v)
//
func (fctq *FileCategoryTypeQuery) Select(field string, fields ...string) *FileCategoryTypeSelect {
	selector := &FileCategoryTypeSelect{config: fctq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := fctq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return fctq.sqlQuery(), nil
	}
	return selector
}

func (fctq *FileCategoryTypeQuery) prepareQuery(ctx context.Context) error {
	if fctq.path != nil {
		prev, err := fctq.path(ctx)
		if err != nil {
			return err
		}
		fctq.sql = prev
	}
	if err := filecategorytype.Policy.EvalQuery(ctx, fctq); err != nil {
		return err
	}
	return nil
}

func (fctq *FileCategoryTypeQuery) sqlAll(ctx context.Context) ([]*FileCategoryType, error) {
	var (
		nodes       = []*FileCategoryType{}
		withFKs     = fctq.withFKs
		_spec       = fctq.querySpec()
		loadedTypes = [1]bool{
			fctq.withLocationType != nil,
		}
	)
	if fctq.withLocationType != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, filecategorytype.ForeignKeys...)
	}
	_spec.ScanValues = func() []interface{} {
		node := &FileCategoryType{config: fctq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		if withFKs {
			values = append(values, node.fkValues()...)
		}
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, fctq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := fctq.withLocationType; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*FileCategoryType)
		for i := range nodes {
			if fk := nodes[i].location_type_file_category_type; fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(locationtype.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "location_type_file_category_type" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.LocationType = n
			}
		}
	}

	return nodes, nil
}

func (fctq *FileCategoryTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fctq.querySpec()
	return sqlgraph.CountNodes(ctx, fctq.driver, _spec)
}

func (fctq *FileCategoryTypeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := fctq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (fctq *FileCategoryTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   filecategorytype.Table,
			Columns: filecategorytype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: filecategorytype.FieldID,
			},
		},
		From:   fctq.sql,
		Unique: true,
	}
	if ps := fctq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fctq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fctq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fctq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, filecategorytype.ValidColumn)
			}
		}
	}
	return _spec
}

func (fctq *FileCategoryTypeQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(fctq.driver.Dialect())
	t1 := builder.Table(filecategorytype.Table)
	selector := builder.Select(t1.Columns(filecategorytype.Columns...)...).From(t1)
	if fctq.sql != nil {
		selector = fctq.sql
		selector.Select(selector.Columns(filecategorytype.Columns...)...)
	}
	for _, p := range fctq.predicates {
		p(selector)
	}
	for _, p := range fctq.order {
		p(selector, filecategorytype.ValidColumn)
	}
	if offset := fctq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fctq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FileCategoryTypeGroupBy is the builder for group-by FileCategoryType entities.
type FileCategoryTypeGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fctgb *FileCategoryTypeGroupBy) Aggregate(fns ...AggregateFunc) *FileCategoryTypeGroupBy {
	fctgb.fns = append(fctgb.fns, fns...)
	return fctgb
}

// Scan applies the group-by query and scan the result into the given value.
func (fctgb *FileCategoryTypeGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := fctgb.path(ctx)
	if err != nil {
		return err
	}
	fctgb.sql = query
	return fctgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (fctgb *FileCategoryTypeGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := fctgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (fctgb *FileCategoryTypeGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(fctgb.fields) > 1 {
		return nil, errors.New("ent: FileCategoryTypeGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := fctgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (fctgb *FileCategoryTypeGroupBy) StringsX(ctx context.Context) []string {
	v, err := fctgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (fctgb *FileCategoryTypeGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = fctgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filecategorytype.Label}
	default:
		err = fmt.Errorf("ent: FileCategoryTypeGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (fctgb *FileCategoryTypeGroupBy) StringX(ctx context.Context) string {
	v, err := fctgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (fctgb *FileCategoryTypeGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(fctgb.fields) > 1 {
		return nil, errors.New("ent: FileCategoryTypeGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := fctgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (fctgb *FileCategoryTypeGroupBy) IntsX(ctx context.Context) []int {
	v, err := fctgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (fctgb *FileCategoryTypeGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = fctgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filecategorytype.Label}
	default:
		err = fmt.Errorf("ent: FileCategoryTypeGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (fctgb *FileCategoryTypeGroupBy) IntX(ctx context.Context) int {
	v, err := fctgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (fctgb *FileCategoryTypeGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(fctgb.fields) > 1 {
		return nil, errors.New("ent: FileCategoryTypeGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := fctgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (fctgb *FileCategoryTypeGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := fctgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (fctgb *FileCategoryTypeGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = fctgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filecategorytype.Label}
	default:
		err = fmt.Errorf("ent: FileCategoryTypeGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (fctgb *FileCategoryTypeGroupBy) Float64X(ctx context.Context) float64 {
	v, err := fctgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (fctgb *FileCategoryTypeGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(fctgb.fields) > 1 {
		return nil, errors.New("ent: FileCategoryTypeGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := fctgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (fctgb *FileCategoryTypeGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := fctgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (fctgb *FileCategoryTypeGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = fctgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filecategorytype.Label}
	default:
		err = fmt.Errorf("ent: FileCategoryTypeGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (fctgb *FileCategoryTypeGroupBy) BoolX(ctx context.Context) bool {
	v, err := fctgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (fctgb *FileCategoryTypeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range fctgb.fields {
		if !filecategorytype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := fctgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fctgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (fctgb *FileCategoryTypeGroupBy) sqlQuery() *sql.Selector {
	selector := fctgb.sql
	columns := make([]string, 0, len(fctgb.fields)+len(fctgb.fns))
	columns = append(columns, fctgb.fields...)
	for _, fn := range fctgb.fns {
		columns = append(columns, fn(selector, filecategorytype.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(fctgb.fields...)
}

// FileCategoryTypeSelect is the builder for select fields of FileCategoryType entities.
type FileCategoryTypeSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (fcts *FileCategoryTypeSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := fcts.path(ctx)
	if err != nil {
		return err
	}
	fcts.sql = query
	return fcts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (fcts *FileCategoryTypeSelect) ScanX(ctx context.Context, v interface{}) {
	if err := fcts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (fcts *FileCategoryTypeSelect) Strings(ctx context.Context) ([]string, error) {
	if len(fcts.fields) > 1 {
		return nil, errors.New("ent: FileCategoryTypeSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := fcts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (fcts *FileCategoryTypeSelect) StringsX(ctx context.Context) []string {
	v, err := fcts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (fcts *FileCategoryTypeSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = fcts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filecategorytype.Label}
	default:
		err = fmt.Errorf("ent: FileCategoryTypeSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (fcts *FileCategoryTypeSelect) StringX(ctx context.Context) string {
	v, err := fcts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (fcts *FileCategoryTypeSelect) Ints(ctx context.Context) ([]int, error) {
	if len(fcts.fields) > 1 {
		return nil, errors.New("ent: FileCategoryTypeSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := fcts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (fcts *FileCategoryTypeSelect) IntsX(ctx context.Context) []int {
	v, err := fcts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (fcts *FileCategoryTypeSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = fcts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filecategorytype.Label}
	default:
		err = fmt.Errorf("ent: FileCategoryTypeSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (fcts *FileCategoryTypeSelect) IntX(ctx context.Context) int {
	v, err := fcts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (fcts *FileCategoryTypeSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(fcts.fields) > 1 {
		return nil, errors.New("ent: FileCategoryTypeSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := fcts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (fcts *FileCategoryTypeSelect) Float64sX(ctx context.Context) []float64 {
	v, err := fcts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (fcts *FileCategoryTypeSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = fcts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filecategorytype.Label}
	default:
		err = fmt.Errorf("ent: FileCategoryTypeSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (fcts *FileCategoryTypeSelect) Float64X(ctx context.Context) float64 {
	v, err := fcts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (fcts *FileCategoryTypeSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(fcts.fields) > 1 {
		return nil, errors.New("ent: FileCategoryTypeSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := fcts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (fcts *FileCategoryTypeSelect) BoolsX(ctx context.Context) []bool {
	v, err := fcts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (fcts *FileCategoryTypeSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = fcts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filecategorytype.Label}
	default:
		err = fmt.Errorf("ent: FileCategoryTypeSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (fcts *FileCategoryTypeSelect) BoolX(ctx context.Context) bool {
	v, err := fcts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (fcts *FileCategoryTypeSelect) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range fcts.fields {
		if !filecategorytype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for selection", f)}
		}
	}
	rows := &sql.Rows{}
	query, args := fcts.sqlQuery().Query()
	if err := fcts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (fcts *FileCategoryTypeSelect) sqlQuery() sql.Querier {
	selector := fcts.sql
	selector.Select(selector.Columns(fcts.fields...)...)
	return selector
}
